### ISSUE TITLE
How to install in HA? 

### ISSUE THREAD

**Issue by joerican** [joncar/ha-fpa#1]
Sorry for the noob question, but how do I get this working in HA? I tried via HACS but it didn't work. Any help would be great, i just got the Brezza tonight because I saw you had this integration! :D

**Comment by joncar** [comment]
Cool! You download all of the files into your configuration directory under custom_components/fpa. Restart HA and it should see it. I made this to scratch my own itch, and as you probably know have near zero free time for some reason :), so I didn't spend any time with making it easy to install using HACS.

Good luck! As far as I know you will be the first person besides me to use it. Let me know how it goes for you.

**Comment by joerican** [comment]
Ok I copied the files over, found the integration under formula pro advanced wifi, I was able to get through the wizard for username/password however no entities appeared. I see this in the logs:

First occurred: 8:33:27 PM (5 occurrences)
Last logged: 8:38:30 PM

Error while setting up fpa platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fpa/sensor.py", line 39, in async_setup_entry
    await api.connect_to_device(device.device_id)
  File "/usr/local/lib/python3.9/site-packages/pyfpa/__init__.py", line 344, in connect_to_device
    await self.get_device_details(device_id)
  File "/usr/local/lib/python3.9/site-packages/pyfpa/__init__.py", line 324, in get_device_details
    device.update_details(j)
  File "/usr/local/lib/python3.9/site-packages/pyfpa/__init__.py", line 157, in update_details
    self.shadow.update(json["shadow"])
  File "/usr/local/lib/python3.9/site-packages/pyfpa/__init__.py", line 126, in update
    self.low_water = r['hardware']['alerts']["lowWater"]
KeyError: 'lowWater'

**Comment by joncar** [comment]
I think I see the problem and have fixed it. Your device is so new it hasn't gotten all of the alerts yet. Try updating the integration files and restarting HA (manifest.json and sensor.py have changed).

If that doesn't fix it please add this to your configuration.yaml so we get better debugging info in your Home Assistant log file:
```
logger:
  logs:
    pyfpa: debug
```
