### ISSUE TITLE
Error Config flow could not be loaded

### ISSUE THREAD

**Issue by joerican** [joncar/ha-fpa#2]
I did an update to HA and the integration no longer was working, I removed the integration, downloaded this new build and I get an error of :

Error
Config flow could not be loaded

I also see this in the logs:
Error occurred loading configuration flow for integration fpa: No module named 'pyfpa'
2:53:26 PM – (ERROR) config_entries.py

**Comment by joncar** [comment]
Whoops. That is my fault. I renamed the import because the name was taken, but missed updating it in config_flow.py. Should be good now!

**Comment by joerican** [comment]
Thanks Again! That fixed it.
