### ISSUE TITLE
Add Setup instructions to README.md

### ISSUE THREAD

**Issue by dmellenthin** [joncar/ha-fpa#3]
I am interested in enabling this integration, and contributing to make this available for others.

I tried simplistically adding the contents of this repo to my config:/custom_components/ha-fpa, and adding fpa: username and password  values to my configuration.yaml

Are there other steps to make this work?

I greatly appreciate your efforts!
Daniel

**Comment by joncar** [comment]
Once you've copied the files (I put it in the custom_components/fpa directory, but I don't know if this matters), all you need to do is add it in the Integrations UI. [![Open your Home Assistant instance and start setting up a new integration.](https://my.home-assistant.io/badges/config_flow_start.svg)](https://my.home-assistant.io/redirect/config_flow_start/?domain=fpa)

**Comment by dmellenthin** [comment]
Got it! Thank You for the incredibly quick response.  I see sensor.baby_brezza, and that is working as expected :)
