### ISSUE TITLE
What is a bottle Id???

### ISSUE THREAD

**Issue by MorganMarchese** [joncar/ha-fpa#5]
Hi Jon! Thanks so much for your efforts in building a baby brezza integration. I am trying to get this working but it's unfortunately very unclear to me what the appropriate values are for "bottle Id". The readme says the bottle Ids are found in the sensor attributes, but when I output the attributes in HA I don't see any references to bottle Id.

I also spent some time looking over the sensor code in the repo and the underlying Fpa() implementation and I still can't find anything that even hints at a list of proper values.

I saw a video on Reddit of a guy using this interface/HA to get voice controls via Alexa. In the video he asks Alexa to "make a 2oz bottle" and then it dispenses. Is this integration really capable of changing attribute values? If so, please help me understand how to get it working! Or just where to find a list of valid bottle Ids would be great too.

Thanks again!

**Comment by joncar** [comment]
In the baby brezza app you can add custom bottle definitions with size, temperature, etc. These get a unique id on their cloud service. Once you define some they'll show up as attributes in home assistant and you can use the id in the start bottle service.

**Comment by MorganMarchese** [comment]
Thank you so much! I didn't even think to check in the brezza app for additional setup because all I wanted was a cool HA automation 🤣

Thanks Jon you rock.
