### ISSUE TITLE
Non-functional in HA 2023.5 -- Fix Below

### ISSUE THREAD

**Issue by seandop** [joncar/ha-fpa#6]
For those who are still trying to use this in 2023, make the following change below on line 24 in __init__.py:

![image](https://github.com/joncar/ha-fpa/assets/37277849/443942ca-abec-49bb-a992-5ade7e47834d)

**Comment by joncar** [comment]
Thanks! Can you double check the code in https://github.com/joncar/ha-fpa/tree/user/joncar/fix-2023.5 works for you? I don't have the device anymore to check for myself.

**Comment by jkhalil** [comment]
Seems to work. Do you plan on merging to master so we can integrate the github repo into hacs?

**Comment by joncar** [comment]
Done. Thanks!
